version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: sudo bash -c "$(curl -fsSL https://s3.amazonaws.com/tools.nanobox.io/bootstrap/ci.sh)"
      - run: nanobox run php test.php
